name: Java CI

on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'GeyserMC/Geyser'
          submodules: true

      - name: Patch JVM target to Java 21
        run: |
          sed -i 's/8.1.1/8.1.7/; s/com.github.johnrengelman/io.github.goooler.shadow/; s/name = "shadow"/name = "shadow-gradle-plugin"/' gradle/libs.versions.toml
          sed -i 's/com.github.johnrengelman.shadow/io.github.goooler.shadow/' build-logic/src/main/kotlin/geyser.shadow-conventions.gradle.kts
          sed -i 's/target(8)/target(17)/' common/build.gradle.kts

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 'current'

      - name: Build with Gradle
        run: gradle build

      - name: Upload velocity variants
        uses: actions/upload-artifact@v4
        with:
          name: Geyser-Velocity
          path: bootstrap/velocity/build/libs/Geyser-Velocity.jar
          if-no-files-found: error

      - name: Upload all variants
        uses: actions/upload-artifact@v4
        with:
          name: all
          path: bootstrap/*/build/libs/Geyser-*.jar
          if-no-files-found: error
