name: Java CI

on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'GeyserMC/Geyser'
          submodules: true

      - name: Patch JVM target to Java 21
        run: |
          sed -i 's/6.3.0/8.4/; s/JavaLanguageVersion.of(17)/JavaLanguageVersion.of(21)/' build.gradle.kts
          sed -i 's/7.1.3-SNAPSHOT/8.1.1/' build-logic/build.gradle.kts
          sed -i 's/target(17)/target(21)/' build-logic/src/main/kotlin/geyser.base-conventions.gradle.kts

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 'current'

      - name: Build with Gradle
        run: gradle build

      - name: Upload velocity variants
        uses: actions/upload-artifact@v4
        with:
          name: Geyser-Velocity
          path: bootstrap/velocity/build/libs/Geyser-Velocity.jar
          if-no-files-found: error

      - name: Upload all variants
        uses: actions/upload-artifact@v4
        with:
          name: all
          path: bootstrap/*/build/libs/Geyser-*.jar
          if-no-files-found: error
