name: Java CI

on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Gradle
        uses: GeyserMC/actions/setup-gradle-composite@master
        with:
          setup-java_java-version: 21
          checkout_repository: 'GeyserMC/Geyser'

      - name: Patch JVM target to Java 21
        run: |
          sed -i 's/8.1.1/8.3.5/; s/com.github.johnrengelman/com.gradleup.shadow/; s/name = "shadow"/name = "shadow-gradle-plugin"/' gradle/libs.versions.toml
          sed -i 's/com.github.johnrengelman.shadow/com.gradleup.shadow/' build-logic/src/main/kotlin/geyser.shadow-conventions.gradle.kts
          sed -i 's/target(8)/target(21)/' common/build.gradle.kts

      - name: Build with Gradle
        run: gradle build --stacktrace

      - name: Upload velocity variants
        uses: actions/upload-artifact@v4
        with:
          name: Geyser-Velocity
          path: bootstrap/velocity/build/libs/Geyser-Velocity.jar
          if-no-files-found: error

      - name: Upload all variants
        uses: actions/upload-artifact@v4
        with:
          name: all
          path: bootstrap/*/build/libs/Geyser-*.jar
          if-no-files-found: error
